#!/bin/bash
################################################################################
# 02: Hardware Configuration
# Configure /boot/firmware/config.txt for display, camera, SPI, I2C
################################################################################

set -e

echo "=== Configuring Hardware ==="

CONFIG_FILE="/boot/firmware/config.txt"
CONFIG_APPEND="$(dirname "$0")/../config/config.txt.append"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ ERROR: $CONFIG_FILE not found!"
    echo "   Are you running Raspberry Pi OS?"
    exit 1
fi

# Backup original config
echo "→ Backing up $CONFIG_FILE..."
cp "$CONFIG_FILE" "${CONFIG_FILE}.backup-$(date +%Y%m%d-%H%M%S)"

# Check if our config is already applied
if grep -q "# RPi 5 AI Robot Configuration" "$CONFIG_FILE"; then
    echo "⚠️  Hardware configuration already applied, skipping..."
    exit 0
fi

echo "→ Appending hardware configuration..."

# Append our configuration
cat >> "$CONFIG_FILE" << 'EOF'

################################################################################
# RPi 5 AI Robot Configuration
# Auto-generated by setup script
################################################################################

# 3.5" SPI Touch Display (piscreen)
dtoverlay=piscreen,speed=18000000,drm,rotate=0,penirq_recheck_delay_usecs=100
dtparam=spi=on
dtparam=i2c_arm=on

# Fan control (lower activation threshold for active cooler)
dtparam=fan_temp0=40000
dtparam=fan_temp0_hyst=5000
dtparam=fan_temp1=60000
dtparam=fan_temp2=70000

# Camera Module 3 (IMX708)
camera_auto_detect=1

# Enable UART for debugging (optional)
enable_uart=1

EOF

echo "✓ Hardware configuration applied"
echo ""
echo "  Configuration added:"
echo "    - piscreen display overlay (3.5\" SPI touch)"
echo "    - SPI and I2C enabled"
echo "    - Fan temperature thresholds"
echo "    - Camera Module 3 support"
echo ""
echo "  These changes will take effect after reboot."
echo ""

exit 0
