#!/bin/bash
################################################################################
# 03: Audio Configuration
# Detect USB audio device and configure ALSA
################################################################################

set -e

echo "=== Configuring Audio ==="

# Detect USB Audio device
echo "→ Detecting USB Audio device..."
USB_CARD=$(aplay -l | grep -i "USB Audio" | head -n 1 | sed -n 's/card \([0-9]\+\):.*/\1/p')

if [ -z "$USB_CARD" ]; then
    echo "⚠️  WARNING: No USB Audio device found!"
    echo "   Available audio devices:"
    aplay -l
    echo ""
    echo "   Please connect a USB audio device and run this script again,"
    echo "   or manually edit /etc/asound.conf after setup."
    
    # Use default card as fallback
    USB_CARD=0
    echo "   Using fallback: card $USB_CARD"
fi

echo "✓ USB Audio detected on card $USB_CARD"

# Create ALSA configuration
echo "→ Creating /etc/asound.conf..."

cat > /etc/asound.conf << EOF
# ALSA configuration for RPi 5 AI Robot
# USB Audio Device is card $USB_CARD
# Auto-generated by setup script

# Set default PCM device to USB Audio with plug layer
pcm.!default {
    type plug
    slave.pcm "hw:${USB_CARD},0"
}

# Default control device - USB Audio
ctl.!default {
    type hw
    card $USB_CARD
}
EOF

echo "✓ ALSA configuration created"

# Test audio
echo "→ Testing audio output..."
if speaker-test -D default -t wav -c 2 -l 1 > /dev/null 2>&1; then
   echo "✓ Audio test successful"
else
    echo "⚠️  Audio test failed. Check connections and run setup again if needed."
fi

echo ""
echo "  ALSA configured for:"
echo "    Card: $USB_CARD (USB Audio)"
echo "    Config: /etc/asound.conf"
echo ""

exit 0
